### ISSUE TITLE
Configurable Views

### ISSUE THREAD

**Issue by grayxr** [FbF/Laravel-Contact-Form#3]
I was thinking it would be nice to have configurable views (or maybe only the layout, like column width, etc.) so that we wouldn't have to overwrite the source view file in order to change the layout.

**Comment by neilcrookes** [comment]
The main view that is rendered, is configurable already. You can create your own view, and @include the form partial, or write your own form if you really need to. To get the controller to render your own view, change the value in the 'view' key in the package's config file that you've published into your app's config directory.

**Comment by grayxr** [comment]
Thanks!
